[rsshub]
host = "https://rsshub.top/"

[[rss]]
name = "Hacker News"
url = "https://news.ycombinator.com/rss"

[[rss]]
name = "Google"
url = "https://blog.google/rss/"

[[rsshub_feeds]]
name = "Deepmind"
url = "/deepmind/blog"

[[rsshub_feeds]]
name = "Anthropic Engineering"
url = "/anthropic/engineering"
